### ISSUE TITLE
if system dark, site is dark but the text is not white for home page

### ISSUE THREAD

**Issue by mesopelagique** [doc4d/go-mobile#92]
![Screenshot 2022-02-15 at 15 17 54](https://user-images.githubusercontent.com/59135882/154109924-be775f17-fe6b-4b97-b13c-546793c9973f.png)

if I change and come back no issue

If I edit using dev mode
![Screenshot 2022-02-15 at 16 26 55](https://user-images.githubusercontent.com/59135882/154109893-0a523ba9-a9f5-4755-9b0d-a0c325ddf51b.png)

maybe here https://github.com/doc4d/go-mobile/blob/main/src/pages/index.js#L54 there is not yet dark mode information

**Comment by mesopelagique** [comment]
any fix? I reproduce

then last deploy  failed
Error:  Client bundle compiled with errors therefore further build is impossible.
Error: Image i18n/fr/docusaurus-plugin-content-docs/version-19-R5/tutorials/actions/img/listform-taskslist-forms-section.png used in i18n/fr/docusaurus-plugin-content-docs/version-19-R5/tutorials/actions/adding-actions-template.md not found.
    at async Promise.all (index 4)
Error: Process completed with exit code 1.

**Comment by arnaud4d** [comment]
Docusaurus was upgraded and we don't have the issue with dark mode
Regarding failed deployment we are working on it (pb with crowdin synchro), it' s now ok
